-- MySQL Script generated by MySQL Workbench
-- ter 11 set 2018 10:33:34 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `CodUsuário` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CodUsuário`),
  UNIQUE INDEX `CodUsuário_UNIQUE` (`CodUsuário` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `idMesa` INT NOT NULL AUTO_INCREMENT,
  `QtdCadeiras` INT NOT NULL,
  UNIQUE INDEX `idMesa_UNIQUE` (`idMesa` ASC) VISIBLE,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Garçom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Garçom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Garçom` (
  `Nome` VARCHAR(45) NOT NULL,
  `RG` INT NOT NULL,
  `CPF` INT(11) NOT NULL,
  `Idade` INT NOT NULL,
  `Endereço` VARCHAR(50) NOT NULL,
  `Telefone` INT NOT NULL,
  `Usuário_CodUsuário` INT NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`Usuário_CodUsuário`),
  CONSTRAINT `fk_Garçom_Usuário1`
    FOREIGN KEY (`Usuário_CodUsuário`)
    REFERENCES `mydb`.`Usuário` (`CodUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cozinheiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cozinheiro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cozinheiro` (
  `Nome` VARCHAR(45) NOT NULL,
  `RG` INT NOT NULL,
  `CPF` INT(11) NOT NULL,
  `Idade` INT NOT NULL,
  `Endereço` VARCHAR(50) NOT NULL,
  `Telefone` INT NOT NULL,
  `Usuário_CodUsuário` INT NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`Usuário_CodUsuário`),
  CONSTRAINT `fk_Cozinheiro_Usuário1`
    FOREIGN KEY (`Usuário_CodUsuário`)
    REFERENCES `mydb`.`Usuário` (`CodUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gerente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `Nome` VARCHAR(45) NOT NULL,
  `RG` INT NOT NULL,
  `CPF` INT(11) NOT NULL,
  `Idade` INT NOT NULL,
  `Endereço` VARCHAR(50) NOT NULL,
  `Telefone` INT NOT NULL,
  `Usuário_CodUsuário` INT NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`Usuário_CodUsuário`),
  CONSTRAINT `fk_Gerente_Usuário1`
    FOREIGN KEY (`Usuário_CodUsuário`)
    REFERENCES `mydb`.`Usuário` (`CodUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Opcional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Opcional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Opcional` (
  `CodOpcional` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`CodOpcional`),
  UNIQUE INDEX `CodOpcional_UNIQUE` (`CodOpcional` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complemento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Complemento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Complemento` (
  `CodComplemento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`CodComplemento`),
  UNIQUE INDEX `CodComplemento_UNIQUE` (`CodComplemento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prato` (
  `CodPrato` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`CodPrato`),
  UNIQUE INDEX `CodPrato_UNIQUE` (`CodPrato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bebida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `CodBebida` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`CodBebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `Mesa_idMesa` INT NOT NULL,
  `Complemento_CodComplemento` INT NOT NULL,
  `Prato_CodPrato1` INT NOT NULL,
  `Bebida_CodBebida` INT NOT NULL,
  `Opcional_CodOpcional` INT NOT NULL,
  `Garçom_Usuário_CodUsuário` INT NOT NULL,
  `Cozinheiro_Usuário_CodUsuário` INT NOT NULL,
  PRIMARY KEY (`Mesa_idMesa`, `Garçom_Usuário_CodUsuário`),
  INDEX `fk_Mesa_has_Prato_Mesa1_idx` (`Mesa_idMesa` ASC) VISIBLE,
  INDEX `fk_Mesa_has_Prato_Complemento1_idx` (`Complemento_CodComplemento` ASC) VISIBLE,
  INDEX `fk_Mesa_has_Prato_Prato1_idx` (`Prato_CodPrato1` ASC) VISIBLE,
  INDEX `fk_Mesa_has_Prato_Bebida1_idx` (`Bebida_CodBebida` ASC) VISIBLE,
  INDEX `fk_Mesa_has_Prato_Opcional1_idx` (`Opcional_CodOpcional` ASC) VISIBLE,
  INDEX `fk_Pedido_Garçom1_idx` (`Garçom_Usuário_CodUsuário` ASC) VISIBLE,
  INDEX `fk_Pedido_Cozinheiro1_idx` (`Cozinheiro_Usuário_CodUsuário` ASC) VISIBLE,
  CONSTRAINT `fk_Mesa_has_Prato_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `mydb`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_has_Prato_Complemento1`
    FOREIGN KEY (`Complemento_CodComplemento`)
    REFERENCES `mydb`.`Complemento` (`CodComplemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_has_Prato_Prato1`
    FOREIGN KEY (`Prato_CodPrato1`)
    REFERENCES `mydb`.`Prato` (`CodPrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_has_Prato_Bebida1`
    FOREIGN KEY (`Bebida_CodBebida`)
    REFERENCES `mydb`.`Bebida` (`CodBebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_has_Prato_Opcional1`
    FOREIGN KEY (`Opcional_CodOpcional`)
    REFERENCES `mydb`.`Opcional` (`CodOpcional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Garçom1`
    FOREIGN KEY (`Garçom_Usuário_CodUsuário`)
    REFERENCES `mydb`.`Garçom` (`Usuário_CodUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cozinheiro1`
    FOREIGN KEY (`Cozinheiro_Usuário_CodUsuário`)
    REFERENCES `mydb`.`Cozinheiro` (`Usuário_CodUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
